### ISSUE TITLE
PR comment is confusing

### ISSUE THREAD

**Issue by kenorb** [ludeeus/action-shellcheck#11]
Build: [644229756](https://github.com/EA31337/EA-Tester/runs/644229756?check_suite_focus=true#step:4:12) is green, but...

GHA comment suggests something else on the EA31337/EA-Tester/pull/181 PR:
![image](https://user-images.githubusercontent.com/266306/81012897-3a03a000-8e52-11ea-821f-d03ce05a7ac2.png)

It suggests there are no errors:

> No errors or shellcheck is disabled

but the next line suggests that there are some issues:

> The files above have some shellcheck issues.

Same for shfmt:

> No errors or shfmt is disabled

but the next line suggests that there are some formatting problems.

Maybe the action shouldn't comment anything on no errors?

Also, it would be great to show which build triggered the comment (GH-12).

**Comment by ludeeus** [comment]
That is another action, not this one.
This does not comment
