### ISSUE TITLE
problem-matcher appears to be  matched in the to-test repo

### ISSUE THREAD

**Issue by quodlibetor** [ludeeus/action-shellcheck#21]
My PRs just started failing with:

```
##[error]Unable to process command '::add-matcher::.github/problem-matcher.json' successfully.
##[error]Could not find file '/home/runner/work/chrono/chrono/.github/problem-matcher.json'.
```

Example: https://github.com/chronotope/chrono/pull/447/checks?check_run_id=839552633

**Comment by quodlibetor** [comment]
Seems to be related to https://github.com/actions/toolkit/issues/56 which suggests that the docs say that this should have worked, but that maybe copying the file onto the host filesystem would fix it.

**Comment by ludeeus** [comment]
Yeah, it probably needs to be in the container, or there is some magic path that should be used.
I like the problem matcher feature, so I will investigate later this week on how to safely bring it back.

**Comment by quodlibetor** [comment]
yeah it seems great in general. Thanks for your work on this action!
