### ISSUE TITLE
Container action is only supported on Linux

### ISSUE THREAD

**Issue by Bhupesh-V** [ludeeus/action-shellcheck#27]
Running shellcheck using the action, fails on `macos-latest`

[Here](https://github.com/Bhupesh-V/dotman/actions/runs/223362439) is a demo

It would be nice if this action works for macOS as well for cross-OS script testing

**Comment by ludeeus** [comment]
I will try to look into it.
But the example <https://github.com/ludeeus/action-shellcheck#example> can be used as a standalone action and when you do that, it will always run on ubuntu
