### ISSUE TITLE
Release 0.6.0 with `scandir` option

### ISSUE THREAD

**Issue by al-the-x** [ludeeus/action-shellcheck#30]
Thanks for this handy action! Very cleanly implemented. As a reminder, you have a new feature advertised in the `README` and available in `master` that hasn't been released yet: the `scandir` option.

https://github.com/ludeeus/action-shellcheck/compare/0.5.0...master

Keep up the great work!

**Comment by ludeeus** [comment]
The reason for that is quite simple, that addition was not added by me, and I have not have had the time to personally test it yet.
Once I do, it will be released :+1:

**Comment by ludeeus** [comment]
This was released with <https://github.com/ludeeus/action-shellcheck/releases/tag/1.0.0>
