### ISSUE TITLE
Support excluding files not just directories

### ISSUE THREAD

**Issue by jthurne** [ludeeus/action-shellcheck#41]
## Checklist

- [X] This Feature Request only contains 1 request (if you have multiple open multiple feature requests).

## The idea

Right now, it is possible to tell the action to ignore directories that match a particular pattern. But it is not possible to ignore a specific file that may live within one of the directories. Being able to ignore files (vs directories) would make it possible to ignore some scripts in a directory but not all of them.

This could be useful in ignoring scripts produced by third-parties (that we don't want to check), like [Gradle's gradlew script](https://docs.gradle.org/current/userguide/gradle_wrapper.html).

## Implementation

Improve the step that excludes paths to also exclude files that match the pattern given in the `ignore` config property. Maybe use grep instead of how it's implemented now (that would allow folks to use grep's patterns to match files/directories to exclude).

**Comment by katexochen** [comment]
This would be really useful. Are you planing to implement this feature?
