### ISSUE TITLE
Hide Shellcheck output from the public

### ISSUE THREAD

**Issue by luni3359** [ludeeus/action-shellcheck#54]
## Checklist

- [x] This Feature Request only contains 1 request (if you have multiple open multiple feature requests).

## The idea

This is more of a question but there was no template for it. Is there any way to make Shellcheck exit out to Code Scanning Alerts instead? The big red X next to the commits make them seem like they're a bigger problem than they actually are for the scope of my project. It's my first time trying out Github Actions, so when I set up CodeQL I thought Shellcheck was going to behave in the same way.

## Implementation

Shellcheck scans like CodeQL would, and if it finds any errors instead of marking them publicly on the repository, it sends notifications to the repo's Secutiy section under "Code scanning alerts".

## Alternatives

I'm not aware of any, but if you do know please let me know!

## Additional context

It also leaves failure notifications every time it runs while the script hasn't yet been modified, which could also be sent to "Code scanning alerts".

**Comment by ludeeus** [comment]
Until GitHub opens up that section to third-party actions/services (which I doubt will ever happen), that can not be done.

**Comment by luni3359** [comment]
Oh I see, I had no idea that was limited to their own products. Do you know if there's a way to make Shellcheck output as a successful job regardless of how many errors it found to stop it from sending notifications and adding crosses to commits?

**Comment by ludeeus** [comment]
That is how actions are supposed to work, so the only way is to not use it :smile:

**Comment by luni3359** [comment]
Well thanks for the help! I suppose it should be fine if I close the issue then, due to the seemingly lack of support on Github's side.
