### ISSUE TITLE
Support for arm64 instances

### ISSUE THREAD

**Issue by dylanmtaylor** [ludeeus/action-shellcheck#60]
## Checklist

- [X] This Feature Request only contains 1 request (if you have multiple open multiple feature requests).

## The idea

Allow arm64 instances like Amazon's Graviton2/Graviton3 running Ubuntu

## Implementation

How do you see this being implemented?

Add a new variable for arm64 instead of x86 in the yaml and download the appropriate version

## Alternatives

Are there any alternative solutions or features you've considered?

No

## Additional context

N/A

**Comment by ludeeus** [comment]
In what case do you need your linters to run on custom runners?
The code is already hosted on github, and you would never pass along any secrets to those jobs

**Comment by dylanmtaylor** [comment]
> In what case do you need your linters to run on custom runners? The code is already hosted on github, and you would never pass along any secrets to those jobs

We use philips-labs/terraform-aws-github-runner to run a farm on self-hosted runners already, as we use a LOT of minutes of build time (several thousand per month), far beyond what's economical at the cost of GitHub runners. We are using arm64 for terraform/packer builds because they work on Graviton instances and are very cost-effective, and I wanted to be able to just run all of our jobs with the runners that we already built by adding our tags to use self-hosted runners.

**Comment by ludeeus** [comment]
I see, you should be able to split it up and run linters on default runners (which should go fast if you do not have millions of script files).

Anyway, at this point, there are no plans to add it, the reason for it is that I can not test or verify it myself.
