### ISSUE TITLE
Create new release

### ISSUE THREAD

**Issue by malt3** [ludeeus/action-shellcheck#64]
## Checklist

- [x] This Feature Request only contains 1 request (if you have multiple open multiple feature requests).

## The idea

Create a new release of this action to include ignore pattern https://github.com/ludeeus/action-shellcheck/commit/c2b45ddc5f85874384c94057c796192604f417d6

## Implementation

Create release via GitHub

## Additional context

Using the new feature together with dependabot is hard as dependabot will try to downgrade this action to the latest release.

**Comment by ludeeus** [comment]
A release will come when I'm ready, currently there are still issues preventing me for doing that.
If you need other features use SHA or branch name.
You can also tell dependably to ignore versions.
