### ISSUE TITLE
Support v1, v2, etc tags

### ISSUE THREAD

**Issue by pavelsaman** [ludeeus/action-shellcheck#65]
## The idea

Support `v1` tag.

## Implementation

Add the tag to commit `94e0aab`.

## Additional context

Some people might want to use version 1 of this action:

```
- name: Run ShellCheck
  uses: ludeeus/action-shellcheck@v1
```

But that's currently not supported.

**Comment by ludeeus** [comment]
Tags are "supported" used, you find them here <https://github.com/ludeeus/action-shellcheck/tags>

**Comment by pavelsaman** [comment]
> Tags are "supported" used, you find them here https://github.com/ludeeus/action-shellcheck/tags

I was referring to this https://github.com/actions/toolkit/blob/master/docs/action-versioning.md that is some people choose to bind to the latest version by using e.g. `v1` that points to the latest version of that major version (1.*).

But ok, I understand you don't want to support this.
Thanks for the reply.

**Comment by katexochen** [comment]
This would be a feature I'd appreciate. It would be nice to use tags prefixed by a 'v': `v2.0.0` like most actions do (compare `uses: actions/checkout@v3`)
