### ISSUE TITLE
No facility for excluding subtrees

### ISSUE THREAD

**Issue by rwalker-apple** [ludeeus/action-shellcheck#7]
It is common for projects to be exposed to shell scripts from other, third party projects added with, for example, `git subtree`

EXCLUDE_DIRS allows this action to skip specified directories, to accommodate such a case.

**Comment by rwalker-apple** [comment]
tired of seeing this in my dashboard

**Comment by luizm** [comment]
@rwalker-apple https://github.com/luizm/action-sh-checker maybe it works for you

**Comment by rwalker-apple** [comment]
we've moved on.  using restyled.io now
