### ISSUE TITLE
New release plan

### ISSUE THREAD

**Issue by wojsmol** [ludeeus/action-shellcheck#78]
Is there a plan for a new release to address  https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/. I see changes in `master` branch but stable release will be better.

cc @ludeeus

**Comment by ludeeus** [comment]
No

**Comment by Frederick888** [comment]
@ludeeus Will you accept contributions?

**Comment by AlecRust** [comment]
@Frederick888 the fix is already in `master` no contribution is needed here, just a release.

**Comment by jaapmarcus** [comment]
To be exact:

https://github.com/ludeeus/action-shellcheck/commit/9634fec4edda42bb6b9116e4c653e49ad304793c

**Comment by Frederick888** [comment]
I see. Sorry for jumping the gun.
