### ISSUE TITLE
Release request

### ISSUE THREAD

**Issue by croissanne** [ludeeus/action-shellcheck#79]
Could another stable release be made? The default branch contains a bunch of useful features like https://github.com/ludeeus/action-shellcheck/pull/44, but it's not always desirable to use the latest version of a github action.

**Comment by ludeeus** [comment]
It will be done by the end of this year or early next year.
You do not have to use `@master` if you do not want to.
You can also pin it to a specific SHA like `@6d3f514f44620b9d4488e380339edc0d9bbe2fba` (HEAD at the time of writing) which IMO is much better than tags anyway.
