### ISSUE TITLE
Release request: post-1.1.0

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [ludeeus/action-shellcheck#80]
Hi.

First of all, thank you for this action. I've been using it with success in several projects.

Recently, there was a bump in the underlying `shellcheck` version which, via fixing some issues, surfaced some others.

I was caught off guard, but still was able to fix those issues. Upon visiting this actions' page I found that I can specify `with` element `version`, to fix the underlying `shellcheck` version to use, but this seems to exist only in the `master` branch.

Since I consider CI to be less stable if I use `master` (which is effectively what caught me off guard in the first place) I'm requesting a post-1.1.0 release, if possible.

Thank you.

**Comment by jaapmarcus** [comment]
See:
https://github.com/ludeeus/action-shellcheck/issues/78
or 
https://github.com/ludeeus/action-shellcheck/issues/79

Use instead
https://github.com/hestiacp/hestiacp/blob/34bd8d630e1a040f22ecc425766e05802c3a6bd7/.github/workflows/lint.yml#L31-L32

**Comment by paulo-ferraz-oliveira** [comment]
I see... thanks for the references.

**Note**: I did search the issues, but not closed ones 😢
