### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by josegonzalez** [ludeeus/action-shellcheck#81]
## Checklist

- [x] This Feature Request only contains 1 request (if you have multiple open multiple feature requests).

## The idea

It would be nice to make a release. The [diff](https://github.com/ludeeus/action-shellcheck/compare/1.1.0...master) since the last release is a bit long :)

## Implementation

Not sure if you have automated releases, but probably just clicking the release button and generating the readme would be good enough.

## Alternatives

Using the `master` release of this repo would be an alternative, but using a released version would be great so we know what goes into the release vs potentially floating to something not-bc.

## Additional context

I use this action in Dokku and it's great! I was updating actions and noticed this one doesn't have a recent release, hence the issue.

**Comment by ludeeus** [comment]
https://github.com/ludeeus/action-shellcheck/releases/tag/2.0.0
