### ISSUE TITLE
support arm64 builds?

### ISSUE THREAD

**Issue by karolcomgy** [ludeeus/action-shellcheck#89]
## The idea

It'd be great to have arm64 builds of this action. Currently it doesn't seem to work well:

```
Run ludeeus/action-shellcheck@master
  with:
    scandir: ./bin
    disable_matcher: false
    format: gcc
    version: stable
Run if [[ "Linux" == "macOS" ]]; then
Run "/runner/_work/_actions/ludeeus/action-shellcheck/master/shellcheck" --version
/runner/_work/_temp/fff516ca-6c1[2](https://github.comXXX/actions/runs/4064350496/jobs/7015480234#step:4:2)-[4](https://github.com/XXX/actions/runs/4064350496/jobs/7015480234#step:4:4)20c-ad1a-[5](https://github.com/XXX/actions/runs/4064350496/jobs/7015480234#step:4:5)ba8f8d4ba81.sh: line 1: /runner/_work/_actions/ludeeus/action-shellcheck/master/shellcheck: cannot execute binary file: Exec format error
Error: Process completed with exit code 12[6](https://github.com/messhelden/XXX/actions/runs/4064350496/jobs/7015480234#step:4:6).
``` 

## Implementation

Perhaps this build process for arm64 still works: https://github.com/koalaman/aarch64-builder

## Alternatives

Can't see any.

## Additional context

We're almost 100% graviton shop on AWS, this is slightly blocking us.

**Comment by ludeeus** [comment]
Untill GitHub provide action runners for it, this is not sometthing I will add.

**Comment by bwhitehead0** [comment]
can we revisit this? we use graviton instances with github enterprise for some of our pipelines. would prefer to not have to one-off our shellcheck scans.
